### ISSUE TITLE
stream read less than specified amount, expected 1073422928, found 0 (IDFGH-10433)

### ISSUE THREAD

**Issue by amanenk** [espressif/esp-coredump#4]
I am trying to read coredump that I copied from flash to sd card. I have an elf file of my firmware.
I see  that there is a stream.read() exception  raised but when i run stream.read() just after creation of the stream it doesn't rise the exception. And the expected size of the stream does not fit any of my files.

``` python
from esp_coredump import CoreDump
import os

elf_path = "C:/test\.pio\\build\lolin_d32\\firmware.elf"

# print  the size of the test app ELF file
print("Size of the test app ELF file: ", os.path.getsize(elf_path), "bytes")


bin_path = "D:/coredump_3221.bin"

# print the size of the test app corefile
print("Size of the test app corefile: ", os.path.getsize(bin_path), "bytes")
# Instantiate the coredump object
coredump = CoreDump(chip='esp32',core=bin_path,core_format='elf', prog=elf_path)
coredump.info_corefile()  #  print the info of the test app corefile
# coredump.dbg_corefile()  #  run GDB debug session with provided ELF file
```
as a result i see the next error

```
Size of the test app ELF file:  16086728 bytes
Size of the test app corefile:  36588 bytes
Traceback (most recent call last):
  File "C:\test\scripts\coredump.py", line 16, in <module>      
    coredump.info_corefile()  #  print the info of the test app corefile
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\esp_coredump\coredump.py", line 465, in info_corefile
    core_header_info_dict = self.get_core_header_info_dict(e_machine=self.exe_elf.e_machine)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\esp_coredump\coredump.py", line 140, in get_core_header_info_dict
    chip_rev = self.extract_chip_rev_from_elf()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\esp_coredump\coredump.py", line 109, in extract_chip_rev_from_elf
    elf = ElfFile(elf_path=self.core)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\esp_coredump\corefile\elf.py", line 119, in __init__
    self.read_elf(elf_path)
  File "C:\Python311\Lib\site-packages\esp_coredump\corefile\elf.py", line 135, in read_elf
    self._model = self._struct.parse(elf_bytes)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 291, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 303, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 315, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 2123, in _parse
    subobj = sc._parsereport(stream, context, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 315, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 2656, in _parse
    return self.subcon._parsereport(stream, context, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 315, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 2278, in _parse
    subobj = sc._parsereport(stream, context, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 315, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 2123, in _parse
    subobj = sc._parsereport(stream, context, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 315, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 2656, in _parse
    return self.subcon._parsereport(stream, context, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 315, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 4298, in _parse
    obj = self.subcon._parsereport(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 315, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 851, in _parse
    return stream_read(stream, length, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 91, in stream_read
    raise StreamError("stream read less than specified amount, expected %d, found %d" % (length, len(data)), path=path)
construct.core.StreamError: Error in path (parsing) -> load_segments -> data
stream read less than specified amount, expected 1073422928, found 0
```

I found that coredup that is stored to the flash does not start with right bytes so i have created a function that searches for start sequence of coredump

```c++
void copyCoredumpPartitionToSDCard(int16_t boot_number)
{

    esp_core_dump_init();
    esp_core_dump_summary_t *summary = (esp_core_dump_summary_t *)malloc(sizeof(esp_core_dump_summary_t));
    if (summary)
    {
        // esp_log_level_set("esp_core_dump_elf", ESP_LOG_VERBOSE); // so that func below prints stuff.. but doesn't actually work, have to set logging level globally through menuconfig
        log.printf("Retrieving core dump summary..\n");
        esp_err_t err = esp_core_dump_get_summary(summary);
        if (err == ESP_OK)
        {
            // get summary function already pints stuff
            log.printf("Getting core dump summary ok.\n");
            // todo: do something with dump summary
        }
        else
        {
            log.printf("Getting core dump summary not ok. Error: %d\n", (int)err);
            log.printf("Probably no coredump present yet.\n");
            log.printf("esp_core_dump_image_check() = %d\n", esp_core_dump_image_check());
        }
        free(summary);
    }

    // implement esp_core_dump_image_get()
    size_t addr;
    size_t size;
    esp_err_t err = esp_core_dump_image_get(&addr, &size);
    if (err != ESP_OK)
    {
        log.printf("esp_core_dump_image_get() failed with error: %d\n", (int)err);
        return;
    }
    log.printf("esp_core_dump_image_get() ok. addr: %d, size: %d\n", addr, size);

    String coredump_path = "/coredump_" + String(boot_number - 1) + ".bin";
    FS *sd_fs = get_sd_fs();
    if (sd_fs == NULL)
    {
        log.printf("sd_fs == NULL\n");
        return;
    }
    File partition_file = sd_fs->open(coredump_path.c_str(), FILE_APPEND);
    // read the flash
    uint8_t buffer[256];

    int sequence_index = -1;
    for (int i = 0; i < size; i += 256)
    {
        err = esp_flash_read(esp_flash_default_chip, buffer, addr + i, 256);
        if (err != ESP_OK)
        {
            log.printf("esp_flash_read() failed with error: %d\n", (int)err);
            return;
        }
        if (sequence_index == -1)
        {
            char sequence[4] = {0x7f, 0x45, 0x4c, 0x46};
            for (int j = 0; j < 256 - sizeof(sequence); j++)
            {
                if (buffer[j] == sequence[0] && buffer[j + 1] == sequence[1] && buffer[j + 2] == sequence[2] && buffer[j + 3] == sequence[3])
                {
                    sequence_index = j;
                    break;
                }
            }
            // write buffer to flash from sequence_index
            log.printf("sequence_index: %d\n", sequence_index);
            partition_file.write(buffer + sequence_index, 256 - sequence_index);
            continue;
        }
        log.printf("esp_flash_read() ok.\n");
        partition_file.write(buffer, 512);
        // todo append buffer to file
    }
    log.printf("esp_flash_read() ok.\n");
    partition_file.close();
    log.println("Coredump partition copied to SD card");
}
```

**Comment by dobairoland** [comment]
Hi @amanenk. I'm sorry for the late reply. Have you found a solution or this still needs to be addressed?
