### ISSUE TITLE
ValueError: invalid literal for int() with base 16: '' (IDFGH-12154)

### ISSUE THREAD

**Issue by MassimilianoMontagni** [espressif/esp-coredump#5]
I can't longer decode crash dumps because I'm getting a `ValueError`, the crash is from an `ESP32-C6` with `esp-idf v5.2`

`esp-coredump --chip esp32s3 info_corefile --print-mem --core-format elf --core crash.elf firmware.elf`

<details>
  <summary>esp-coredump output</summary>
 
```sh
espcoredump.py v1.10.0
===============================================================
==================== ESP32 CORE DUMP START ====================

Crashed task handle: 0x40841798, name: 'wifi', GDB name: 'process 1082398616'
Crashed task is not in the interrupt context
Panic reason: assert failed: block_locate_free heap_tlsf.c:476 (block_size(block) >= size)

================== CURRENT THREAD REGISTERS ===================
pc             <unavailable>
lbeg           <unavailable>
lend           <unavailable>
lcount         <unavailable>
sar            <unavailable>
ps             <unavailable>
threadptr      <unavailable>
br             <unavailable>
scompare1      <unavailable>
acclo          <unavailable>
acchi          <unavailable>
m0             <unavailable>
m1             <unavailable>
m2             <unavailable>
m3             <unavailable>
expstate       <unavailable>
f64r_lo        <unavailable>
f64r_hi        <unavailable>
f64s           <unavailable>
fcr            <unavailable>
fsr            <unavailable>
a0             <unavailable>
a1             <unavailable>
a2             <unavailable>
a3             <unavailable>
a4             <unavailable>
a5             <unavailable>
a6             <unavailable>
a7             <unavailable>
a8             <unavailable>
a9             <unavailable>
a10            <unavailable>
a11            <unavailable>
a12            <unavailable>
a13            <unavailable>
a14            <unavailable>
a15            <unavailable>

==================== CURRENT THREAD STACK =====================
#0  <unavailable> in ?? ()

======================== THREADS INFO =========================
  Id   Target Id         Frame 
* 1    process 1         <unavailable> in ?? ()


       TCB             NAME PRIO C/B  STACK USED/FREE
---------- ---------------- -------- ----------------
Traceback (most recent call last):
  File "/opt/homebrew/bin/esp-coredump", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/esp_coredump/scripts/espcoredump.py", line 40, in main
    temp_core_files = espcoredump.info_corefile()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/esp_coredump/coredump.py", line 566, in info_corefile
    self.print_threads_info(task_info)
  File "/opt/homebrew/lib/python3.11/site-packages/esp_coredump/coredump.py", line 355, in print_threads_info
    pxEndOfStack = int(self.gdb_esp.parse_tcb_variable(tcb_addr, 'pxEndOfStack'), 16)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 16: ''
```
</details>

**Comment by erhankur** [comment]
@MassimilianoMontagni you have esp32c6 but you are trying to run the script with the wrong chip param?

Please try this

```
esp-coredump --chip esp32c6 info_corefile --print-mem --core-format elf --core crash.elf firmware.elf
```

**Comment by MassimilianoMontagni** [comment]
@erhankur Sorry, feeling quite dumb now ahah. I copy-pasted from another project and I forgot to change the chip param

Thanks for the support
